#include "IS2020.h"
#include <Arduino.h>

/* Company IDs for vendor dependent commands */
#define IEEEID_BTSIG    0x001958

/* Status codes */
#define AVRCP_STATUS_INVALID_COMMAND    0x00
#define AVRCP_STATUS_INVALID_PARAM    0x01
#define AVRCP_STATUS_PARAM_NOT_FOUND    0x02
#define AVRCP_STATUS_INTERNAL_ERROR   0x03


#define AVRCP_STATUS_SUCCESS      0x04
#define AVRCP_STATUS_OUT_OF_BOUNDS    0x0b
#define AVRCP_STATUS_INVALID_PLAYER_ID    0x11
#define AVRCP_STATUS_PLAYER_NOT_BROWSABLE 0x12
#define AVRCP_STATUS_NO_AVAILABLE_PLAYERS 0x15
#define AVRCP_STATUS_ADDRESSED_PLAYER_CHANGED 0x16

/* Packet types */
#define AVRCP_PACKET_TYPE_SINGLE  0x00
#define AVRCP_PACKET_TYPE_START   0x01
#define AVRCP_PACKET_TYPE_CONTINUING  0x02
#define AVRCP_PACKET_TYPE_END   0x03

/* PDU types for metadata transfer */
#define AVRCP_GET_CAPABILITIES    0x10
#define AVRCP_LIST_PLAYER_ATTRIBUTES  0X11
#define AVRCP_LIST_PLAYER_VALUES  0x12
#define AVRCP_GET_CURRENT_PLAYER_VALUE  0x13
#define AVRCP_SET_PLAYER_VALUE    0x14
#define AVRCP_GET_PLAYER_ATTRIBUTE_TEXT 0x15
#define AVRCP_GET_PLAYER_VALUE_TEXT 0x16
#define AVRCP_DISPLAYABLE_CHARSET 0x17
#define AVRCP_CT_BATTERY_STATUS   0x18
#define AVRCP_GET_ELEMENT_ATTRIBUTES  0x20
#define AVRCP_GET_PLAY_STATUS   0x30
#define AVRCP_REGISTER_NOTIFICATION 0x31
#define AVRCP_REQUEST_CONTINUING  0x40
#define AVRCP_ABORT_CONTINUING    0x41
#define AVRCP_SET_ABSOLUTE_VOLUME 0x50
#define ACRCP_SET_ADDRESSED_PLAYER 0x60
#define AVRCP_SET_BROWSED_PLAYER  0x70
#define AVRCP_GET_FOLDER_ITEMS    0x71
#define AVRCP_CHANGE_PATH   0x72
#define AVRCP_GET_ITEM_ATTRIBUTES 0x73
#define AVRCP_PLAY_ITEM     0x74
#define AVRCP_SEARCH      0x80
#define AVRCP_ADD_TO_NOW_PLAYING  0x90
#define AVRCP_GENERAL_REJECT    0xA0

/* Capabilities for AVRCP_GET_CAPABILITIES pdu */
#define CAP_COMPANY_ID    0x02
#define CAP_EVENTS_SUPPORTED  0x03

#define AVRCP_REGISTER_NOTIFICATION_PARAM_LENGTH 5
#define AVRCP_GET_CAPABILITIES_PARAM_LENGTH 1

#define AVRCP_BATTERY_STATUS_NORMAL   0
#define AVRCP_BATTERY_STATUS_WARNING    1
#define AVRCP_BATTERY_STATUS_CRITICAL   2
#define AVRCP_BATTERY_STATUS_EXTERNAL   3
#define AVRCP_BATTERY_STATUS_FULL_CHARGE  4

/* player attributes */
#define AVRCP_ATTRIBUTE_ILEGAL    0x00
#define AVRCP_ATTRIBUTE_EQUALIZER 0x01
#define AVRCP_ATTRIBUTE_REPEAT_MODE 0x02
#define AVRCP_ATTRIBUTE_SHUFFLE   0x03
#define AVRCP_ATTRIBUTE_SCAN    0x04

/* equalizer values */
#define AVRCP_EQUALIZER_OFF   0x01
#define AVRCP_EQUALIZER_ON    0x02

/* repeat mode values */
#define AVRCP_REPEAT_MODE_OFF   0x01
#define AVRCP_REPEAT_MODE_SINGLE  0x02
#define AVRCP_REPEAT_MODE_ALL   0x03
#define AVRCP_REPEAT_MODE_GROUP   0x04

/* shuffle values */
#define AVRCP_SHUFFLE_OFF   0x01
#define AVRCP_SHUFFLE_ALL   0x02
#define AVRCP_SHUFFLE_GROUP   0x03

/* scan values */
#define AVRCP_SCAN_OFF      0x01
#define AVRCP_SCAN_ALL      0x02
#define AVRCP_SCAN_GROUP    0x03

/* media attributes */
#define AVRCP_MEDIA_ATTRIBUTE_ILLEGAL 0x00
#define AVRCP_MEDIA_ATTRIBUTE_TITLE 0x01
#define AVRCP_MEDIA_ATTRIBUTE_ARTIST  0x02
#define AVRCP_MEDIA_ATTRIBUTE_ALBUM 0x03
#define AVRCP_MEDIA_ATTRIBUTE_TRACK 0x04
#define AVRCP_MEDIA_ATTRIBUTE_N_TRACKS  0x05
#define AVRCP_MEDIA_ATTRIBUTE_GENRE 0x06
#define AVRCP_MEDIA_ATTRIBUTE_DURATION  0x07
#define AVRCP_MEDIA_ATTRIBUTE_LAST  AVRCP_MEDIA_ATTRIBUTE_DURATION

/* play status */
#define AVRCP_PLAY_STATUS_STOPPED 0x00
#define AVRCP_PLAY_STATUS_PLAYING 0x01
#define AVRCP_PLAY_STATUS_PAUSED  0x02
#define AVRCP_PLAY_STATUS_FWD_SEEK  0x03
#define AVRCP_PLAY_STATUS_REV_SEEK  0x04
#define AVRCP_PLAY_STATUS_ERROR   0xFF

/* Notification events */
#define AVRCP_EVENT_STATUS_CHANGED    0x01
#define AVRCP_EVENT_TRACK_CHANGED   0x02
#define AVRCP_EVENT_TRACK_REACHED_END   0x03
#define AVRCP_EVENT_TRACK_REACHED_START   0x04
#define AVRCP_EVENT_PLAYBACK_POS_CHANGED 0x05
#define AVRCP_EVENT_BATT_STATUS_CHANGED 0x06
#define AVRCP_EVENT_SYSTEM_STATUS_CHANGED 0x07
#define AVRCP_EVENT_PLAYER_APPLICATION_SETTING_CHANGED 0x08
#define AVRCP_EVENT_NOW_PLAYING_CONTENT_CHANGED 0x09
#define AVRCP_EVENT_AVAILABLE_PLAYERS_CHANGED 0x0a
#define AVRCP_EVENT_ADDRESSED_PLAYER_CHANGED  0x0b
#define AVRCP_EVENT_UIDS_CHANGED    0x0c
#define AVRCP_EVENT_VOLUME_CHANGED    0x0d

