#include "IS2020.h"

/* Company IDs for vendor dependent commands */
#define IEEEID_BTSIG    0x001958

/* Status codes */
#define AVRCP_STATUS_INVALID_COMMAND    0x00
#define AVRCP_STATUS_INVALID_PARAM    0x01
#define AVRCP_STATUS_PARAM_NOT_FOUND    0x02
#define AVRCP_STATUS_INTERNAL_ERROR   0x03
//from https://github.com/pauloborges/bluez/blob/master/profiles/audio/avrcp.c

#define AVRCP_STATUS_SUCCESS      0x04
#define AVRCP_STATUS_OUT_OF_BOUNDS    0x0b
#define AVRCP_STATUS_INVALID_PLAYER_ID    0x11
#define AVRCP_STATUS_PLAYER_NOT_BROWSABLE 0x12
#define AVRCP_STATUS_NO_AVAILABLE_PLAYERS 0x15
#define AVRCP_STATUS_ADDRESSED_PLAYER_CHANGED 0x16

/* Packet types */
#define AVRCP_PACKET_TYPE_SINGLE  0x00
#define AVRCP_PACKET_TYPE_START   0x01
#define AVRCP_PACKET_TYPE_CONTINUING  0x02
#define AVRCP_PACKET_TYPE_END   0x03

/* PDU types for metadata transfer */
#define AVRCP_GET_CAPABILITIES    0x10
#define AVRCP_LIST_PLAYER_ATTRIBUTES  0X11
#define AVRCP_LIST_PLAYER_VALUES  0x12
#define AVRCP_GET_CURRENT_PLAYER_VALUE  0x13
#define AVRCP_SET_PLAYER_VALUE    0x14
#define AVRCP_GET_PLAYER_ATTRIBUTE_TEXT 0x15
#define AVRCP_GET_PLAYER_VALUE_TEXT 0x16
#define AVRCP_DISPLAYABLE_CHARSET 0x17
#define AVRCP_CT_BATTERY_STATUS   0x18
#define AVRCP_GET_ELEMENT_ATTRIBUTES  0x20
#define AVRCP_GET_PLAY_STATUS   0x30
#define AVRCP_REGISTER_NOTIFICATION 0x31
#define AVRCP_REQUEST_CONTINUING  0x40
#define AVRCP_ABORT_CONTINUING    0x41
#define AVRCP_SET_ABSOLUTE_VOLUME 0x50
#define ACRCP_SET_ADDRESSED_PLAYER 0x60
#define AVRCP_SET_BROWSED_PLAYER  0x70
#define AVRCP_GET_FOLDER_ITEMS    0x71
#define AVRCP_CHANGE_PATH   0x72
#define AVRCP_GET_ITEM_ATTRIBUTES 0x73
#define AVRCP_PLAY_ITEM     0x74
#define AVRCP_SEARCH      0x80
#define AVRCP_ADD_TO_NOW_PLAYING  0x90
#define AVRCP_GENERAL_REJECT    0xA0

/* Capabilities for AVRCP_GET_CAPABILITIES pdu */
#define CAP_COMPANY_ID    0x02
#define CAP_EVENTS_SUPPORTED  0x03

#define AVRCP_REGISTER_NOTIFICATION_PARAM_LENGTH 5
#define AVRCP_GET_CAPABILITIES_PARAM_LENGTH 1

#define AVRCP_FEATURE_CATEGORY_1  0x0001
#define AVRCP_FEATURE_CATEGORY_2  0x0002
#define AVRCP_FEATURE_CATEGORY_3  0x0004
#define AVRCP_FEATURE_CATEGORY_4  0x0008
#define AVRCP_FEATURE_PLAYER_SETTINGS 0x0010
#define AVRCP_FEATURE_BROWSING      0x0040

#define AVRCP_BATTERY_STATUS_NORMAL   0
#define AVRCP_BATTERY_STATUS_WARNING    1
#define AVRCP_BATTERY_STATUS_CRITICAL   2
#define AVRCP_BATTERY_STATUS_EXTERNAL   3
#define AVRCP_BATTERY_STATUS_FULL_CHARGE  4



